### ISSUE TITLE
Padding in SpatialConvolution?

### ISSUE THREAD

**Issue by PhillipZeratul** [clementfarabet/torch-ios#32]
It seems SpatialConvolution does not have padding functionality. So when I use torch-ios to load a torch7 trained model, the result is incorrect.

Is there a way to fix this?

Here is what I see in torch-ios (SpatialConvolution.lua):
`function SpatialConvolution:__init(nInputPlane, nOutputPlane, kW, kH, dW, dH)`

Here is what it is like in torch7:
`module = nn.SpatialConvolution(nInputPlane, nOutputPlane, kW, kH, [dW], [dH], [padW], [padH])`

**Comment by liamnaka** [comment]
As stated by @soumith , this library is quite outdated. Many of the torch methods are missing newer components.

**Comment by logic1988** [comment]
Yes. I have the same problem. Is there a new solution?
Is the torch official provided the method to generate IOS library?

**Comment by EliseSo** [comment]
same problem here, can't find a proper solution
